### ISSUE TITLE
Could you share the dataset Product?

### ISSUE THREAD

**Issue by PBlithe** [dgliu/TKDE_KDCRec#1]
I have had the great honor of reading your paper published on TKDE with great benefit. But there are some questions. You mentioned the dataset Product in your paper, but didn't provide a link to it. The dataset is of great value for unbiased research. Can you please share the link to the data. I will be grateful if you do.

**Comment by dgliu** [comment]
Hi, thanks for your attention to our work.

The Product is a private dataset provided by Huawei Noah's Ark Lab, the partner of this work. Unfortunately, they have no plans to open-source this dataset, and we can no longer access it after the cooperation ends.

Alternatively, I suggest using other industrial scenario datasets, such as KuaiRec and KuaiRand.

For other questions, you can always contact me by email :)

**Comment by dgliu** [comment]
> I have had the great honor of reading your paper published on TKDE with great benefit. But there are some questions. You mentioned the dataset Product in your paper, but didn't provide a link to it. The dataset is of great value for unbiased research. Can you please share the link to the data. I will be grateful if you do.

Hi, thanks for your attention to our work.

The Product is a private dataset provided by Huawei Noah's Ark Lab, the partner of this work. Unfortunately, they have no plans to open-source this dataset, and we can no longer access it after the cooperation ends.

Alternatively, I suggest using other industrial scenario datasets, such as KuaiRec and KuaiRand.

For other questions, you can always contact me by email :)
